version: '3.8'

services:
  redis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"

  backend:
    image: authenticationproject
    container_name: myauthenticationproject
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis



